config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'company', to: 'static_pages#company', as: 'company'
  get 'gterms', to: 'static_pages#gterms', as: 'gterms'
  get 'service', to: 'static_pages#service', as: 'service'
  get 'mention', to: 'static_pages#mention', as: 'mention'
  get 'contact', to: 'contacts#index', as: 'contact'
  get 'team_members', to: 'team_members#_team_members', as: 'team_members'
  resources :contacts, only: [:new, :create]

  resources :categories, only: [:show] do
    resources :products, only: [:show]
  end

  resources :promotions, only: [:index]
  resources :comments

  root 'static_pages#home'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def is_active(index)
    index == 0 ? 'active' : ''
  end

  def are_multiple(params)
    params.count() > 1 ? 'multiple' : 'only-one'
  end

  def active_page(page_path)
    current_page?(page_path) ? 'active-nav' : ''
  end

  def is_background(category)
    (category.acceuil_photo.present? && category.active) ? category.acceuil_photo : category.background
  end
  def static_map_for(lat, lng, options = {})
    params = {
      :center => [lat, lng].join(","),
      :zoom => 17,
      :size => "400x300",
      :markers => [lat, lng].join(","),
      :sensor => true
      }.merge(options)

    query_string =  params.map{|k,v| "#{k}=#{v}"}.join("&")
    image_tag "http://maps.googleapis.com/maps/api/staticmap?#{query_string}", alt: '3n-map', class: "threen-map"
  end


end

app/views/static_pages/_partners.html.erb
<% if @partners.first.photos.present? %>
  <h2 class="section-title"> Nos Partenaires </h2>
  <div class="container partners">
    <div class="row">
      <div class="col-md-12">
        <div id="Carousel" class="carousel slide">
          <!-- ol class="carousel-indicators">
          <% @partners.first.photos.in_groups_of(3, false).each_with_index do |partner, index| %>
          <li data-target="#Carousel" data-slide-to="<%= index %>" class="<%= is_active(index) %>"></li>
          <% end %>
        </ol -->
        <!-- Carousel items -->
        <div class="carousel-inner">
          <% @partners.first.photos.in_groups_of(3, false).each_with_index do |partner, index| %>
          <div class="item <%= is_active(index) %>">
            <div class="row">
              <% partner.each do |photo| %>
              <div class="col-md-4">
                <% if photo.partner_url.present? %>
                  <%= link_to image_tag(photo.cont.url, class:"img-responsive center-block"), photo.partner_url, target: '_blank' %>
                <% else %>
                  <%= image_tag photo.cont.url, class:"img-responsive center-block" %>
                <% end %>
              </div>
              <% end %>
            </div>
          </div>
          <% end %>
        </div><!--.carousel-inner-->
        <a data-slide="prev" href="#Carousel" class="left carousel-control">‹</a>
        <a data-slide="next" href="#Carousel" class="right carousel-control">›</a>
      </div><!--.Carousel-->
    </div>
  </div>
  </div>
<% end %>

app/views/static_pages/company.html.erb
<div class="company">
  <div class="company-header"></div>
  <div class="container">
    <div class="col-lg-11 col-lg-offset-1">
      <ol class="breadcrumb">
    	  <li><%= link_to "Acceuil", root_path %></li>
    	  <li class="active">A propos</li>
    	</ol>
      <div class="company-body">
        <div class="row">
          <h1 class="title">A propos de 3N-Secure</h1>
          <table class="company-categ">
            <td>
              • Systèmes d'alarme<br>
              • Vidéosurveillance IP<br>
              • Analogique et HD<br>
              • Vidéophone / interphone<br>
              • Contrôle d'accès<br>
              • Barrières automatiques et accessoires<br>
              • Vidéosurveillance pour véhicule IP et HD<br>
              • Détecteurs de métaux explosifs et scanner d'inspection de bagages
            </td>
            <td>

              • Antennes antivol<br>
              • Dés activeurs, tags et accessoires<br>
              • Détection incendie<br>
              • Miroirs de sécurité<br>
              • Tourniquets tripodes, couleurs rapides et portillons d'accès<br>
              • Portails coulissants<br>
              • Portes basculantes et accessoires<br>
              • Solutions de pointage contrôleurs de rondes<br>

            </td>
          </table>
          <table class="company-products">
            <td>
              <%= image_tag("alarme.jpg")  %>
              <h3 class="red">Systèmes d'alarme :</h3>
              <p>Nos systèmes de détection d'intrusion et d'alarme (Filaire, sans Fil ou Hybride) sont innovants. Nous les réalisons sur mesure suivant vos besoins et selon la configuration de votre bâtiment ou habitation. 24h/24, nous assurons un service technique de garde.</p>
            </td>
            <td>
              <%= image_tag("video.jpg")  %>
              <h3 class="red">Vidéosurveillance :</h3>
              <p>A l'intérieur et à l'extérieur, nous installons des caméras Analogiques, IP et HD performantes afin de surveiller vos habitations, locaux et vous prévenir des intrusions et situations non désirées.</p>
            </td>
            <td>
              <%= image_tag("acces.jpg")  %>
              <h3 class="red">Contrôle d'accès :</h3>
              <p>Afin de contrôler, connaître les mouvements et établir un historique, nos solutions de contrôle d'accès sont optimales. Elles vous permettront d'autoriser ou d'interdire les entrées/sorties d'une zone définie suivant différents critères (horaires, calendrier, fonctions, personnel…). Nous vous proposons des systèmes efficaces par badges, tags, codes, biométrie (empreintes digitales)…</p>
            </td>
          </table>
          <table class="company-tarif">
            <td>
              <strong> </strong>
              <p>
                <strong>
                  Nos prix et tarifs sont bien étudiés et très attractifs.
                  Nos devis sont rapides et GRATUITS.
                </strong> <br>
                Si vous cherchez à installer un système d'alarme, vidéosurveillance,
                contrôle d'accès ou domotique, pensez à
                3N-Secure. Pour toutes informations
                Contactez-nous au <strong class="red">+216 71 70 58 58</strong>
                ou <strong class="red">55 58 00 21 </strong>
              </p>
            </td>
            <td>
              <%= image_tag("sav.jpg") %>
            </td>
          </table>

          <p class="description">
            <strong>Conseil :</strong> <br/><br/>
            Nos experts étudient avec vous les solutions adaptées à vos exigences
            sécuritaires et budgétaires. Nous  vous garantissons des solutions
            sur mesure, pour tout type de bâtiment : habitat, commerce ou grande
            structure!
            De plus, nous nous attachons à optimiser la performance et la pérennité
            de vos installations par des réponses technologiques adaptées et des
            services personnalisés. 
          </p>
          <p class="description">
            <strong>Nos atouts :</strong> <br/><br/>
            &emsp;- Expertise, savoir-faire et innovation technologique en matière de sécurité électronique.<br/>
            &emsp;- Des équipements à la pointe de la technologie.<br/>
            &emsp;- Réactivité et l'écoute du client 24 H/24H 7J/7J.<br/>
            &emsp;- Un suivi permanent de la qualité de nos prestations.<br/>
            &emsp;- Haute qualification technique.<br/>
            &emsp;- Mobilité géographique dans tout le pays.<br/>
            &emsp;- Optimisation des solutions et ajustement au budget du client.
          </p>
          <p class="description">
            <strong>Partenaires et fournisseurs :</strong> <br/><br/>
            Nos partenaires et fournisseurs sont des leaders mondiaux comme
            HIKVISION (Caméras IP, Analogiques et HD, DVRs, NVRs ...), PARADOX
            (systèmes d'alarme), HONEYWELL (détection incendie ESSER), SATEL
            (systèmes d'alarme), ZKTeco (Pointeuses et Contrôle d'accès),
            SECUSCAN (Portiques de sécurité, détecteurs de métaux et Scanners à
            rayons X) , UTEPO (Switchers POE), RG FRANCE (Câble KX6, KX8, Incendie,
            câble CR1/C1...), ULTRACELL et POWER KINGDOM (batteries), PULSAR
            ( Boîtiers et Alimentations ).
          </p>

        </div>

      </div>
    </div>
  </div>
</div>

app/views/static_pages/gterms.html.erb
<div class="container">
  <div class="col-lg-11 col-lg-offset-1">
    <ol class="breadcrumb">
      <li><%= link_to "Acceuil", root_path %></li>
      <li class="active"> Conditions générales de la garantie </li>
    </ol>
    <div class="cgu-body">
      <div class="row">
        <h1 class="title">Conditions générales de la garantie</h1>
        <div class="cgu-terms">
          <ol>
            <li>
              La garantie du constructeur ne couvre pas 
              <ol>
                <li>
                    - Les accessoires vendus avec les produits (télécommande, tête
                    de récepteur, câble d’alimentation  ou de connections, Haut-parleur, ampoules, chargeurs..)
                 </li>
                 <li>
                    - Les consommables.
                  </li>
                  <li>
                    - Toutes mauvaises manipulations (trace de liquides, casse,
                    réparations à l’extérieur, choc électrique, rayures,
                    inversement  de fils, problème système informatique ou
                    mauvaise programmation afficheurs…)
                   </li>
              </ol>
            </li>
            <li>
              En cas de produit livre par 3N-Secure
              <ol>
                <li>
                  - Le client doit examiner  soigneusement les produits à la livraison.
                </li>
                <li>
                  - Le client doit éventuellement tester leur bon fonctionnement.
                </li>
                <li>
                  - En cas de toutes, le client doit apposer les réserves nécessaires sur le bon de livraison.
                </li>
                <li>
                  - En cas d’anomalie (rayures, produit non conforme ou non fonctionnels..), le client doit écrire et signer le motif de son refus sur le bon de livraison ; la marchandise sera ramenée à 3N-Secure par les livreurs et  livrée du nouveau, le lendemain si le produit est disponible.
                </li>
                <li>
                  - Il est recommandé au client de conserver l’emballage d’origine durant toute la durée de la garantie, ce dernier étant requis en cas de retour de la marchandise au S.A.V. et chez les fabricants.
                </li>
                <li>
                  - Aucune réclamation concernant ces points ne sera prise en considération après livraison.
                </li>
                <li>
                  - En cas d’absence du client au moment de la livraison  la marchandise lui sera livrée selon la disponibilité de notre planning.
                </li>
              </ol>
            </li>
            <li>
              En cas de produit emporté par le client :
              <ol>
                En présence du vendeur, vérifier :
                <li>
                  - L’état général du produit.
                </li>
                <li>
                  - La présence  de tous les accessoires.
                </li>
                <li>
                  - La présence de la notice explicative.
                </li>
                <li>
                  - Il est recommandé au client de conserver l’emballage d’origine durant toute la durée de la garantie, ce dernier étant requis en cas de retour de la marchandise au  S.A.V. et chez les fabricants
                </li>
                <li>
                  - S’il le souhaite, le client peut se rendre au S.A.V.  afin de tester son achat.
                </li>
                <li>
                  - Aucune réclamation d’un manque d’accessoire ne sera prise en considération après la date d’achat.
                </li>
              </ol>
            </li>
            <li>
              Pour les produits nécessitant des montages électriques spécifiques 
              <br />
              <ol>
                <li>
                  3N-Secure se dégage de toute responsabilité d’anomalie engendrée
                  par un montage non conforme effectué par une société autre que 3N-Secure.
                </li>
              </ol>
            </li>
            <li>
              En cas de changement d’avis :
              <ol>
                <li>
                  Tous nos produits une fois vendus ne sont ni repris ni échangés.
                </li>
              </ol>
            </li>
            <li>
              En cas de panne :
              <ol>
                Le produit doit être ramené au SAV :
                <li>
                  - Avec ticket de caisse ou la facture, 3N-Secure s’engage à :
                </li>
                <li>
                  - Faire établir un diagnostic technique de la panne  par la constructrice
                </li>
                <li>
                  - Communiquer au client l’origine de la panne.
                </li>
                <li>
                  - Réparer le produit sous  30 jours maximum suivant son dépôt au S.A.V.
                </li>
                <li>
                  - Si ce n’est pas le cas, 3N-Secure délivrera un avoir au client.
                  Si la cause de panne est due à une mauvaise manipulation de la part du client, 3N-Secure établira un ordre pour réparation qui sera soumis à l’approbation du client avant toute intervention et ce si le produit se trouve réparable.
                </li>
              </ol>
            </li>
          </ol>

          </div>
          <h2 class="condition">
            LE NON RESPECT DE L’UNE DE CES CONDITIONS PAR LE
            CLIENT, DEGAGE 3N-SECURE DE TOUTE RESPONSABILITE
          </h2>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<%= render 'sliders/slide' %>
<% if @featured_products.present? %>
  <section class="featured">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <%= render 'sliders/featured_products'%>
        </div>
      </div>
    </div>
  </section>
<% end %>

<section class="cat-blocks">
  <div class="container">
    <ul class="row">
      <% @root_categories.categories.each do |root| %>
        <li class="col col-lg-4  col-md-6 col-sm-12 category-photo">
          <div class="box" style="background-image: linear-gradient(to bottom, transparent, transparent),url(<%= is_background(root) %>);">
            <div class="category-description">
              <%= raw(parag_truncate(root.description, 200)) %>
            </div>
            <%= link_to "Voir tous les produits", category_path(root), class: "btn btn-warning" %>
            <%= link_to category_path(root), class:"btn btn-default box-title" do %>
              <span> <%= parag_truncate(root.name.titleize, 30) %> </span>
            <% end %>
          </div>
          <!--
            <%= link_to category_path(root), class:"box-title" do %>
              <h3><%= root.name.titleize %> </h3>
            <% end %>
          -->
        </li>
      <% end %>
    </ul>
  </div>
</section>

<section class="infos">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <div class="box">
          <%= link_to service_path, class:"red" do %>
            <%= image_tag 'sav.png' %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-4 ">
        <div class="box">
          <%= link_to contact_path, class:"red" do %>
            <%= image_tag 'devis.png' %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-4 ">
        <div class="box">
          <%= link_to gterms_path, class:"red" do %>
            <%= image_tag 'garantie.png' %>
          <% end %>
        </div>
      </div>
    </div>

    <hr>


  </div>
</section>
<%= render 'static_pages/partners' %>

app/views/static_pages/inprogress.html.erb
<div class="inprogress">
  <div class="holder">
    <%= image_tag 'logo.png' %>
    <h1 class="red"> Site en development </h1>
  </div>
</div>

<style media="screen">
  body {
    padding-top: 0px;
  }
</style>

app/views/static_pages/mention.html.erb
<div class="container">
  <div class="col-lg-11 col-lg-offset-1">
    <ol class="breadcrumb">
      <li><%= link_to "Acceuil", root_path %></li>
      <li class="active"> Mention Légales </li>
    </ol>
    <div class="cgu-body">
      <div class="row">
        <h1 class="title">Mention Légales</h1>
        <div class="cgu-terms">
          <ol>
            <li>
              Informations mises à disposition
              <ol>
                <li>
                  Les informations communiquées et publiées sur ce site, sont non contractuelles. Le contenu mis à disposition est fourni à titre informatif. L'existence d'un lien du site de la société 3N-Secure vers un autre site ne constitue pas une validation de ce site ou de son contenu. Il appartient à l'internaute
                  d'utiliser ces informations avec discernement et esprit critique.
                 </li>
              </ol>
            </li>
            <li>
              Licence de droit d'usage et copyright
              <ol>
                <li>
                  L'ensemble de ce site relève de la législation Tunisienne et internationale sur le droit d'auteur et de la propriété intellectuelle, aussi bien en ce qui concerne sa forme choix du plan, disposition des matières, moyens d'accès aux données, organisation des données... 
                  <br />
                  Concernant chacun des éléments de son contenu textes, et images. Toutes les reproductions, de tout ou partie de ce site, y compris pour les documents téléchargeables et les représentations sont formellement interdites sauf autorisation expresse du responsable du site.
                 </li>
              </ol>
            </li>
            <li>
              Edition
              <ol>
                <li>
                  Le site, www.3n-secure.tn est édité par 3N-Secure,
                  dont le siège social est au 65 AVENUE HABIB BOURGUIBA 2EME ETAGE APPT N°2, NOUVELLE ARIANA 2080,TUNISIE.
                  Le directeur responsable de la publication est Monsieur Samy NADJAR.
                 </li>
              </ol>
            </li>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/static_pages/service.html.erb
<div class="container">
  <div class="col-lg-11 col-lg-offset-1">
    <ol class="breadcrumb">
      <li><%= link_to "Acceuil", root_path %></li>
      <li class="active"> Service aprés vente </li>
    </ol>
  </div>
  <div class="service">
    <div class="infos-container">
      Nos techniciens vous guident :<br />
      Vous souhaitez faire évoluer votre matériel et vérifier la compatibilité d’un nouveau composant ?<br/>
      Contrôler votre sélection de pièces pour votre toute nouvelle machine personnalisée ?<br/>
      Vous désirez tout simplement être guidé pour trouver le meilleur produit pour votre budget ?<br/>
      Contactez-nous ! Nos techniciens expérimentés se feront un plaisir de répondre à vos interrogations !
      <br />
      Appelez sur le <strong>71 70 58 58</strong> ou nous envoyer un email à l’adresse suivante :
      <strong> sav@3n-secure.tn </strong>.
    </div>
    <div class="description-container">
      Avez-vous besoin d'aide ou du service de réparation ?<br />
      Nous souhaitons que vos produits
      S'il arrivait que votre matériel tombe en panne, vous parviendriez
      facilement à obtenir l'aide dont vous avez besoin, en vous appelant sur
      le <br /><strong>71 70 58 58</strong> ou nous envoyer un email à l’adresse suivante :
      <strong>sav@3n-secure.tn</strong>.
      Les centres SAV de nos fournisseurs tenus par des techniciens qualifiés et
      sont destinés à répondre aux diverses demandes de réparation.<br/> <br/>

 
      Le personnel évalue les produits au moyen de procédures et de matériel de test spécifiques, puis effectue les réparations et les vérifications nécessaires auprès de nos fournisseurs et ce conformément aux normes 3N-Secure. Dans les centres des fournisseurs sont également stockées les différentes pièces de rechange pour chacun de nos produits. La plupart des produits peuvent être réparés, y compris ceux qui ne sont plus couverts par la garantie.
    </div>
  </div>
</div>