config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'company', to: 'static_pages#company', as: 'company'
  get 'gterms', to: 'static_pages#gterms', as: 'gterms'
  get 'service', to: 'static_pages#service', as: 'service'
  get 'mention', to: 'static_pages#mention', as: 'mention'
  get 'contact', to: 'contacts#index', as: 'contact'
  get 'team_members', to: 'team_members#_team_members', as: 'team_members'
  resources :contacts, only: [:new, :create]

  resources :categories, only: [:show] do
    resources :products, only: [:show]
  end

  resources :promotions, only: [:index]
  resources :comments

  root 'static_pages#home'
end

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <h3>Entreprise</h3>
        <ul class="list-unstyled">
          <li><%= link_to "A propos de 3N-Secure", company_path %></li>
          <li><%= link_to "Mentions légales", mention_path %></li>
          <% if @team_members.present? %>
            <li> <%= link_to "Equipe", team_members_path %></li>
          <% end %>
        </ul>
      </div>
      <div class="col-sm-3">
        <h3>Produits</h3>
        <ul class="list-unstyled">
          <% @root_categories.each do |category| %>
            <li><%= link_to category.name.humanize , category_path(category.id) %></li>
          <% end %>
        </ul>
      </div>
      <div class="col-sm-2">
        <h3>Services & support</h3>
        <ul class="list-unstyled">
          <li><%= link_to "Services & support", gterms_path %></li>
          <li><%= link_to "Service Client", contact_path %></li>
        </ul>
      </div>
      <div class="col-sm-4 last">
        <ul class="social">
          <li>
            <a href="https://www.facebook.com/3N-Secure" target="_blank">
              <%= icon "facebook-f fa-2x" %>
            </a>
          </li>
          <li>
            <a href="https://www.instagram.com/3nsecure/" target="_blank">
              <%= icon "instagram fa-2x" %>
            </a>
          </li>

          <li>
            <a href="https://www.linkedin.com/company/10639587?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A10639587%2Cidx%3A1-1-1%2CtarId%3A1480777526685%2Ctas%3A3n-S" target="_blank">
              <%= icon "linkedin fa-2x" %>
            </a>
          </li>
        </ul>
        <div class="company_details">
          <% @details.each do |detail| %>
            <% if detail.address.present? %>
              <div class="details-holder address">
                <i class="fa fa-map-marker fa-2x"> </i>
                <span class="red"><%= detail.address %></span>
              </div>
            <% end %>
            <% if detail.phones.present? %>
              <div class="details-holder phones <%= are_multiple(detail.phones)%>">
                <i class="fa fa-phone fa-2x"> </i>
                <div class="multiple-container">
                  <% detail.phones.each do |phone| %>
                      <span class="red"><%= phone.number %></span>
                  <% end %>
                </div>
              </div>
            <% end %>
            <% if detail.emails.present? %>
              <div class="details-holder emails <%= are_multiple(detail.emails)%>">
                <i class="fa fa-envelope fa-2x"> </i>
                <div class="multiple-container">
                  <% detail.emails.each do |email| %>
                  <span class="red"><%= email.address %></span>
                  <% end %>
                </div>
              </div>
            <% end %>
            <%= link_to 'https://www.google.tn/maps/place/65+Avenue+Habib+Bourguiba,+Tunis/@36.8556737,10.1856833,17z/data=!3m1!4b1!4m8!1m2!2m1!1s65+Avenue+Habib+Bourguiba,+Tunis!3m4!1s0x12fd34b46f9a2f95:0x57111656f64e2937!8m2!3d36.8556737!4d10.1878773?hl=fr', target: '_blank' do %>
              <%= image_tag "3n-map.png", alt: '3n-map' %>
            <% end %>
          <% end %>
        </div>
        <!-- <%= image_tag 'cc.png' %> -->
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top visible-xs">
  <div class="">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag 'logo.png' %></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Acceuil",  root_path %></li>
        <li><%= link_to "Entreprise", company_path %></li>
        <li>
          <a href="#" id="product">Produits</a>
          <ul class="nav navbar-nav navbar-right nav-category">
            <% @root_categories.each do |category| %>
              <li>
                <ul class="catgeory-list">
                  <li class="category-title"><%= text_truncate(category.name,30) %><li>
                  <li class="category-child"><%= link_to text_truncate(category.name,30) , category_path(category) %></li>
                  <% for child_node in category.children %>
                    <li class="category-child"><%= link_to text_truncate(child_node.name,30), category_path(child_node) %></li>
                  <% end %>
                </ul>
              </li>
            <% end %>
          </ul>
        </li>
        <li><%= link_to "Services & support", gterms_path %></li>
        <li><%= link_to "Promotions", promotions_path %></li>
        <li><%= link_to "Devis", contact_path %></li>
      </ul>
    </div>
  </div>
</nav>

<header class="hidden-xs">
  <nav>
    <div class="">
      <div class="row">
        <div class="col-sm-3">
          <%= link_to root_path, class: "brand" do %>
            <%= image_tag 'logo.png' %>
          <% end %>
        </div>
        <div class="col-sm-9">
          <div class="bottom-menu">
            <div class="col-sm-12 details-menu">
              <% @details.each do |detail| %>
                <ul class="list-inline pull-right">
                  <% if detail.phones.present? %>
                    <i class="fa fa-phone red"> </i>
                    <li><%= detail.phones.first.number %></li>
                  <% end %>
                </ul>
              <% end %>
            </div>
            <div class="col-sm-12 nav-menu">
              <ul class="list-inline pull-right">
                <li><%= link_to "Acceuil", root_path, class: active_page(root_path) %></li>
                <li><%= link_to "Entreprise", company_path, class: active_page(company_path) %></li>
                <li id="product"><a href="#">Produits</a></li>
                <li><%= link_to "Services & support", gterms_path, class: active_page(gterms_path) %></li>
                <li><%= link_to "Promotions", promotions_path, class: active_page(promotions_path) %></li>
                <li><%= link_to "Devis", contact_path, class: active_page(contact_path) %></li>
                <!-- <li><a href="#"><i class="fa fa-search"></i></a></li> -->
              </ul>
            </div>
            <div class="col-sm-2 col-sm-offset-3">
              <div class="divider">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
  <%= render template:'categories/index' %>
</header>

app/views/shared/_spinner.html.erb
<div class="spinner">
  <div class="sk-circle">
    <div class="sk-circle1 sk-child"></div>
    <div class="sk-circle2 sk-child"></div>
    <div class="sk-circle3 sk-child"></div>
    <div class="sk-circle4 sk-child"></div>
    <div class="sk-circle5 sk-child"></div>
    <div class="sk-circle6 sk-child"></div>
    <div class="sk-circle7 sk-child"></div>
    <div class="sk-circle8 sk-child"></div>
    <div class="sk-circle9 sk-child"></div>
    <div class="sk-circle10 sk-child"></div>
    <div class="sk-circle11 sk-child"></div>
    <div class="sk-circle12 sk-child"></div>
  </div>
</div>