config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'company', to: 'static_pages#company', as: 'company'
  get 'gterms', to: 'static_pages#gterms', as: 'gterms'
  get 'service', to: 'static_pages#service', as: 'service'
  get 'mention', to: 'static_pages#mention', as: 'mention'
  get 'contact', to: 'contacts#index', as: 'contact'
  get 'team_members', to: 'team_members#_team_members', as: 'team_members'
  resources :contacts, only: [:new, :create]

  resources :categories, only: [:show] do
    resources :products, only: [:show]
  end

  resources :promotions, only: [:index]
  resources :comments

  root 'static_pages#home'
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                        :integer          not null, primary key
#  name                      :string
#  description               :text
#  price                     :decimal(, )
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  document_pdf_file_name    :string
#  document_pdf_content_type :string
#  document_pdf_file_size    :integer
#  document_pdf_updated_at   :datetime
#  category_id               :integer
#  slug                      :string
#  promotion_id              :integer
#  url                       :string
#  new                       :boolean          default(FALSE), not null
#  status                    :string
#  state                     :string
#  user_id                   :integer
#  video_url                 :string
#

class Product < ActiveRecord::Base

  acts_as_commentable

  belongs_to :category
  belongs_to :promotion
  has_many :featured_products

  has_many :comments, as: :commentable

  has_many :images
  accepts_nested_attributes_for :images,
    allow_destroy: true,
    reject_if: lambda { |attributes| attributes[:content].blank? }

  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, presence: true, length: { minimum: 5 }
  validates :description, :category, presence: true

  has_attached_file :document_pdf
  validates_attachment :document_pdf, :content_type => { :content_type => %w(application/pdf), message: "Vous devez inserer un document de format PDF" }

  PRODUCT_STATUS = ["En promotion", "En stock", "Sur commande", "Import en cours"]
  scope :is_new, -> { where(new: true) }
  scope :is_available, -> {where(state: "En stock")}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @category = Category.friendly.find(params[:category_id])
    @product = Product.friendly.find(params[:id])
    @new_comment = Comment.build_from(@product, "", "", "")
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def document_hint(obj)
    if obj.document_pdf?
      content_tag :span do
        concat('PDF actuel:')
        concat(link_to(obj.document_pdf_file_name, obj.document_pdf.url, target: '_blank'))
      end
    end
  end
end

app/views/products/_comments.html.erb
<div class="comments-header">
	<div class="user-infos">
		<div class="avatar-holder">
			<span class="status"></span>
			<%= image_tag 'avatar1.jpg', class: "img-circle" %>
		</div>
		<h3 class="username">3N-Secure QUEST</h3>
	</div>
	<p class="text">Pour répondre à votre question et avoir des conseils </p>
	<p class="submit-text"> Poser votre question <i class="fa fa-chevron-right"></i> </p>
</div>

<div class="comments-body">

	<div class="comments-sender">
		<h3 class="comment-since"> il ya 4 jours</h3>
		<div class="comments-avatar">
			<%= image_tag 'avatar2.jpg', class: "img-circle" %>
			<h3 class="username"> Jack lorem </h3>
		</div>

		<p class="comment-text">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas venenatis magna id sem blandit sagittis. Mauris nec rutrum mauris, convallis imperdiet tortor. Fusce elementum placerat euismod. Fusce interdum, metus in bibendum finibus, erat tortor cursus diam, vitae molestie erat dui at ante.
		</p>
	</div>

	<div class="comments-responder">
		<h3 class="comment-since"> il ya 4 jours</h3>
		<div class="box">
			<div class="row">
				<div class="col-xs-4 col-lg-1">
					<div class="comment-likes">
						<i class="fa fa-heart"></i>
						<span class="likes-count"> +100j'aime </span>
					</div>
				</div>
				<div class="col-xs-8 col-lg-2">
					<div class="user-infos">
						<div class="avatar-holder">
							<span class="status"></span>
							<%= image_tag 'avatar1.jpg', class: "img-circle" %>
						</div>
						<h3 class="username">3N-Secure QUEST</h3>
					</div>
				</div>

				<div class="col-xs-11 col-xs-offset-1 col-lg-9 col-lg-offset-0">
					<p class="comment-text">
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas venenatis magna id sem blandit sagittis. Mauris nec rutrum mauris, convallis imperdiet tortor. Fusce elementum placerat euismod. Fusce interdum, metus in bibendum finibus, erat tortor cursus diam, vitae molestie erat dui at ante.
					</p>
				</div>

			</div>

		</div>
	</div>

	<div class="comments-sender">
		<h3 class="comment-since"> il ya 4 jours</h3>
		<div class="comments-avatar">
			<%= image_tag 'avatar2.jpg', class: "img-circle" %>
			<h3 class="username"> Jack lorem </h3>

		</div>

		<p class="comment-text">
			Vraiment Merci :)
		</p>
	</div>

	<div class="comments-responder">
		<h3 class="comment-since"> il ya 4 jours</h3>
		<div class="box">
			<div class="row">
				<div class="col-xs-4 col-lg-1">
					<div class="comment-likes">
						<i class="fa fa-heart"></i>
						<span class="likes-count"> +100j'aime </span>
					</div>
				</div>
				<div class="col-xs-8 col-lg-2">
					<div class="user-infos">
						<div class="avatar-holder">
							<span class="status"></span>
							<%= image_tag 'avatar1.jpg', class: "img-circle" %>
						</div>
						<h3 class="username">3N-Secure QUEST</h3>
					</div>
				</div>

				<div class="col-xs-11 col-xs-offset-1 col-lg-9 col-lg-offset-0">
					<p class="comment-text">
						You are welcome :)
					</p>
				</div>

			</div>

		</div>
	</div>

	<div class="comments-submit">
	  <div class="row">
	    <div class="form-group">
		    <div class="col-md-10">
		    	<input type="text" class="form-control" placeholder="Laisser un commentaire" />
		    </div>
		    <div class="col-md-2">
		    	<button type="submit" class="btn btn-default btn-block"> Valider </button>
		    </div>
	    </div>
		</div>
	</div>
</div>

app/views/products/_product.html.erb
<div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-0 col-lg-4 col-lg-offset-0">
  <div class="thumbnail">
    <div class="image-container">
      <% if product.new? %>
        <label class="product-status">NEW</label>
        <% if product.promotion.present? %>
          <label class="product-status">-<%= product.promotion.percentage %>%</label>
        <% end %>
      <% end %>
      <% if product.images.present? %>
        <%= image_tag product.images.first.content.url(:small), class:"img-responsive center-block" %>
      <% end %>
      <%= link_to category_product_path(@category , product), class: "product-show" do %>
         <div class="product-link">
            <span class="more"> Voir Produit </span>
          </div>
      <% end %>

    </div>
    <div class="caption">
      <div class="product-infos">
        <div class="row">
          <div class="col-xs-8 col-sm-6 col-md-8">
            <div href="#" data-toggle="tooltip" class="products-name" data-placement="bottom" title="<%= product.name %>"><span ><%= text_truncate(product.name,20) %></span>
          </div></div>
          <div class="col-xs-4 col-sm-6 col-md-4">
            <% if is_present(product.price) %>
              <span class="product-price"> <%= product.price %><sup>DT</sup></span>
            <% end %>
          </div>
        </div>
      </div>
      <!-- <a href="#" class="btn btn-add" role="button">Ajouter au panier </a> -->
    </div>
  </div>
</div>

app/views/products/_sidebar.html.erb
<ul class="categorie-filter">
  <li class="categorie-heading">
    <% if @category.root.icon.present? %>
      <%= image_tag(@category.root.icon.url(:small), :alt => "category-icon") %>
    <% end %>
    <label class="categorie-title">
      <%= active_link_to @category.root.name, category_path(@category.root) %>
    </label>
  </li>
  <li class="categorie-body">
    <% @category.root.children.each do |child| %>
      <ul class="categ-filter">
        <li class="categ-filter-title">
          <%= active_link_to child.name, category_path(child) %>
        </li>
      </ul>
    <% end %>
  </li>
</ul>
<div class="panel panel-default">
  <div class="panel-heading">
    <label class="panel-title">Filtrer par</label>
  </div>
  <div class="panel-body">
    <div class="product-filter">
    	<div class="filter-cat">
	    	<label> Disponibilité</label>
	    	<span class="filter-disp">
	    		<i class="fa fa-square-o available"></i>
	    		<span class="qte-disp">En Stock </span>
	    	</span>
    	</div>
    	<div class="filter-cat">
	    	<label> Prix</label>
	    	<span>Tranche <span class="min-price">0<sup>DT</sup></span></span>
	    	<span class="max-price">4999<sup>DT</sup></span>
    		<input type="text" data-slider-id="filter-rang"
          data-slider-handle="square" class="filter-rang" value="0"
          data-slider-min="0" data-slider-max="4999" data-slider-step="10"
          data-slider-value="[0,4999]"/>

      </div>
    	<div class="filter-cat">
	    	<label> Etat</label>
	    	<span class="filter-disp">
	    		<i class="fa fa-square-o new"></i>
	    		<span class="qte-disp">Nouveau</span>
	    	</span>
    	</div>
    </div>
    <%= search_form_for @q, url: category_path, remote: true do |f| %>
      <%= f.hidden_field :price_gteq, placeholder: "Min Price" %>
      <%= f.hidden_field :price_lteq, placeholder: "Max Price" %>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
	<ol class="breadcrumb">
		<li>
			<%= link_to "Acceuil",  root_path %>
		</li>
		<% if @category.parent.present? %>
			<li><%= link_to text_truncate(@category.parent.name,30), category_path(@category.parent) %></li>
		<% end %>
		<li><%= link_to text_truncate(@category.name, 30), category_path(@category) %></li>
	  <li class="active"> <%= text_truncate(@product.name ,25) %> </li>
	</ol>
	<% if @product.video_url.present? %>
		<div class="embed-responsive embed-responsive-16by9">
			<iframe class="embed-responsive-item" src="" frameborder="0"></iframe>
			<a class="video-url" href="<%= @product.video_url %>"></a>
		</div>
	<% end %>

	<section class="product-infos">
		<div class="row">
			<div class="col-xs-12 col-lg-6">
				<div class="col-xs-12" id="image-preview">
					<%= image_tag @product.images.first.content.url(:xlarge) %>
				</div>
				<div class="row">
					<div class="col-xs-12 col-lg-12 <%= are_multiple(@product.images) %>">
						<% @product.images.each do |image| %>
							<div class="carousel-items col-xs-8 col-xs-offset-2 col-lg-4 col-lg-offset-0">
								<a href="#" class="thumbnail carousel-item" data-image='<%= image_path image.content.url(:large) %>'>
									<%= image_tag image.content.url(:xsmall) %>
								</a>
						</div>
	          <% end %>

					</div>
				</div>
			</div>
			<div class="col-lg-6 product-description">
				<div class="row">
					<div class="col-xs-8 col-lg-9">
						<div class="product-name"> <%= @product.name %></div>
					</div>
					<div class="col-xs-4 col-lg-3">
						<div class="product-stars">
							<i class="fa fa-star full"></i>
							<i class="fa fa-star full"></i>
							<i class="fa fa-star full"></i>
							<i class="fa fa-star full"></i>
							<i class="fa fa-star empty"></i>
						</div>
					</div>
				</div>
				<% if is_present(@product.price) %>
					<span class="product-price"> <%= @product.price %><sup>DT</sup></span>
				<% end %>
				<p class="product-brief">
					<%= @product.description %>
				</p>
				<!-- div class="product-quantity">
					<span class="text"> Quantité</span>
					<div class="input-group spinner">
				    <input type="text" min="0" class="form-control" value="1">
				    <div class="input-group-btn-vertical">
				      <button class="btn btn-default" type="button"><i class="fa fa-caret-up"></i></button>
				      <button class="btn btn-default" type="button"><i class="fa fa-caret-down"></i></button>
				    </div>
				  </div>
					<span class="remaining-products">
						155 Produits Restants
					</span>
				</div -->
				<div class="socials">
					<span class="text"> Partager sur </span>
					<i class="fa fa-facebook social-icon"></i>
					<i class="fa fa-twitter social-icon"></i>
					<i class="fa fa-linkedin social-icon"></i>
					<i class="fa fa-google-plus social-icon"></i>
					<i class="fa fa-youtube social-icon"></i>
				</div>
				<div class="product-command">
					<button class="btn btn-command">Ajouter au panier</button>
					<span class="meta-infos"> garantie: 2ans </span>
				</div>
				<% if @product.document_pdf? %>
					<div class="product-caracteritic">
						caracteristique technique
						<%= link_to @product.document_pdf.url(:original, false), target: "_blank" do %>
							<i class="fa fa-file-pdf-o"></i>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>
		<div class="row product-related">
			<div class="col-sm-12">
				<% if @product.url? %>
				  <div class="embed-responsive embed-responsive-16by9">
				    <iframe class="embed-responsive-item" src="<%= @product.url %>" ></iframe>
				  </div>
				<% end %>
			</div>
		</div>
		<%= render partial: "comments/template", locals: {commentable: @product, new_comment: @comment} %>
	</section>
</div>